### GET notes
GET http://localhost:8080/notes

### POST create notes
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Vegta",
  "content": "Only A Failure Abandons His Principles And Pride."
}

### PUT
PUT http://localhost:8080/notes/1
Content-Type: application/json

{
  "title": "Gabimaru",
  "content": "Appearance doesn't matter at all."
}

### DELETE
DELETE http://localhost:8080/notes/1
